# Generated by Django 6.0.4 on 2026-05-07 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isIncome', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('salary', 'Salary'), ('other', 'Other')], max_length=50)),
                ('paymentMethod', models.CharField(choices=[('credit_card', 'Credit Card'), ('master_card', 'Master Card'), ('visa', 'Visa'), ('mobile_wallet', 'Mobile Wallet')], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
