# Generated by Django 6.0.4 on 2026-04-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isIncome', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('salary', 'Salary'), ('other', 'Other')], max_length=50)),
                ('paymentMethod', models.CharField(choices=[('credit_card', 'Credit Card'), ('master_card', 'Master Card'), ('visa', 'Visa'), ('mobile_wallet', 'Mobile Wallet')], max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
